project_id = "plklxboeramqlwgmhkpc"

[functions.setup-daily-webhook]
verify_jwt = false

[functions.daily-webhook]
verify_jwt = false

[functions.check-transcription]
verify_jwt = false

[functions.upload-recording]
verify_jwt = false
